### ISSUE TITLE
运行app.py时报错

### ISSUE THREAD

**Issue by yinghao2016** [machaoyin/flask_blog#1]
您好，当我下载flask_blog项目到本地电脑，用pycharm打开后，运行app.py时，报错：
Traceback (most recent call last):
  File "E:/PycharmProjects/BlogFlaskLayuiMarkdown/app.py", line 16, in <module>
    from view import *
  File "E:\PycharmProjects\BlogFlaskLayuiMarkdown\view\__init__.py", line 2, in <module>
    from .index import index
  File "E:\PycharmProjects\BlogFlaskLayuiMarkdown\view\index.py", line 3, in <module>
    from model import *
  File "E:\PycharmProjects\BlogFlaskLayuiMarkdown\model\__init__.py", line 2, in <module>
    from .model import *
  File "E:\PycharmProjects\BlogFlaskLayuiMarkdown\model\model.py", line 5, in <module>
    from app import app
  File "E:\PycharmProjects\BlogFlaskLayuiMarkdown\app.py", line 17, in <module>
    app.register_blueprint(blueprint=index)
NameError: name 'index' is not defined

很难理解，明明在有index.py，里面定义了蓝图实例index，为什么还提示蓝图名称未定义。。。
请问，问题出在哪里，您能指教一下吗？

**Comment by zzf8264** [comment]
我也遇到了这个问题 有办法吗

**Comment by yinghao2016** [comment]
> 我也遇到了这个问题 有办法吗

可能需要在views/__init__.py里面定义蓝图‘index’：
比如：
index_blueprint = Blueprint("index_blueprint", __name__)
然后在app.py里面导入蓝图并注册蓝图：
# 从包view导入蓝图，
from view import index_blueprint, blog_blueprint
# 注册蓝图
app.register_blueprint(index_blueprint)

**Comment by aaaaasx** [comment]
您好,这个数据库连接为什么一直显示错误啊RuntimeError: Either 'SQLALCHEMY_DATABASE_URI' or 'SQLALCHEMY_BINDS' must be set.并且每个错误都提示model文件夹有误,在_init_.py里有错 from model import *那里
